messages:
  prefix: "§7[§9Evergene§7]§r "
spawn:
  location:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
database:
  mysql:
    host: "localhost:3001"
    database: "coreplugin"
    username: "root"
    password: "password"