#sets the name of the server to use within the sql database and linking system
Server : "global"
#tells the server to automatically get the server name (is done via a proxy plugin)
automaticServerNameUpdate: false
#defines the spawn location of this server
spawn:
  location:
    world: "world"
    x: 0.0
    y: 65.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
    #you can define more than one spawn and have them for special ranks only "global" is the global spawnpoint. if not overwritten by other rank-spawn
    #not yet implemented
    rank: "global"
database:
  mysql:
    use: false
    host: "localhost:3306"
    database: "coreplugin"
    username: "root"
    password: "password"
    tablePrefix: "Core_"