name: CoreSystem
version: ${project.version}
main: de.polygondev.coresystem.CoreSystem
api-version: 1.13
authors: [ChiAkuma, SamyoFox]
commands:
  spawn:
    description: Go to the spawn
  setspawn:
    description: Set the spawn location
    permission: coresystem.setspawn
  warp:
    description: Teleport to a set warp
  setwarp:
    description: Set a warp point
    permission: coresystem.setwarp
  gm:
    description: change your gamemode or others
    permission: coresystem.gamemode
  tp:
    description: Teleport to a location or to a player
    permission: coresystem.tp
  awoo:
    description: awoo
    permission: coresystem.awoo
  tpa:
    description: Send a teleport request to someone
  tpaccept:
    description: Accept a teleport request
  tpadecline:
    description: Decline a teleport request