name: CoreSystem
version: ${project.version}
main: de.polygondev.coresystem.CoreSystem
api-version: 1.13
authors: [ChiAkuma, SamyoFox]
commands:
  spawn:
    description: Go to the spawn
  setspawn:
    description: Set the spawn location
    permission: coresystem.setspawn
  warp:
    description: Teleport to a set warp
  setwarp:
    description: Set a warp point
    permission: coresystem.setwarp